### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by locon833** [leffj/helper-code-for-uparse#1]
First, Can I directly enter the command "create_otu_table_from_uc_file.py' into the python terminal? It does not recognize it. Or do I enter the script under the document, if so, I get this error:

args = parser.parse_args()
usage: [-h] -i INPUT_FP -o OUTPUT_FP
: error: argument -i/--input_fp is required

I am new to this could you please help. I did not get the uc2otutable.py to work and this is my only option.

Thanks for your time

Nidhi

**Comment by leffj** [comment]
Hi Nidhi,

This should work, but you need to specify an input file path and an output file path. It should look something like this:

create_otu_table_from_uc_file.py -i readmap.uc -o otu_table.txt

It will also depend on how you demultiplexed your raw sequences. This script is meant to be used with another script in the package (prep_fast_for_uparse_paired.py).

Best,
Jon
