### ISSUE TITLE
formatting of .uc file

### ISSUE THREAD

**Issue by colinbrislawn** [leffj/helper-code-for-uparse#2]
Thanks for creating these scripts!

I'm looking for a faster alternative to `uc2otutab.py` and am trying to use your script `create_otu_table_from_uc_file.py`. It throws the Error in uc file formating.

Here is what my .uc file looks like. How can I make it compatible with your script?

```
H   4   253 100.0   +   0   0   =   sample.1.30.3_2 OTU_5;size=644979;
H   25  253 100.0   +   0   0   =   sample.1.30.3_6 OTU_26;size=139253;
H   355 253 100.0   +   0   0   =   sample.1.30.3_7 OTU_326;size=1868;
H   73  253 99.6    +   0   0   253M    sample.1.30.3_24    OTU_70;size=44508;
H   13  253 100.0   +   0   0   =   sample.1.30.3_27    OTU_15;size=230413;
```

**Comment by leffj** [comment]
Hi Colin - 

The script looks for `;barcodelabel=<SAMPLE_ID>;` in the query field. This syntax is from the original Drive5 python scripts but could be changed I suppose.

Also, the target field should have only the OTU ID (not the sizes). You can can relabel the de novo database fasta file you map against using either the `-relabel` flag when clustering otus in usearch v8 or the `fasta_number.py` script from Drive5.

Here are some lines from a recent .uc file I've used:

```
N       *       372     *       .       *       *       *       M01918:213:000000000-AFC1C:1:1101:15775:1331 1:N:0:0;barcode=TAAATATACCCT;barcodelabel=cp83;    *
N       *       374     *       .       *       *       *       M01918:213:000000000-AFC1C:1:1101:15534:1356 1:N:0:0;barcode=TGAGTGGTCTGT;barcodelabel=cp4;     *
H       724     374     98.4    +       0       0       374M    M01918:213:000000000-AFC1C:1:1101:15828:1332 1:N:0:0;barcode=AGCCCTGCTACA;barcodelabel=cp106;   OTU_726
H       254     374     97.3    +       0       0       374M    M01918:213:000000000-AFC1C:1:1101:16172:1350 1:N:0:0;barcode=GACTCAACCAGT;barcodelabel=cp108;   OTU_247
H       33      374     98.1    +       0       0       374M    M01918:213:000000000-AFC1C:1:1101:14664:1370 1:N:0:0;barcode=CATTTCGCACTT;barcodelabel=n9;      OTU_44
```

Jon

**Comment by colinbrislawn** [comment]
Thanks for the help Jon! I think I can get this working for my files. 

> Also, the target field should have only the OTU ID (not the sizes).

Strangely, I want those! This is a really easy way to preserve information about OTU centroids in downstream analysis.

**Comment by leffj** [comment]
OK, great. Let me know if you run into any other issues.

**Comment by colinbrislawn** [comment]
Thanks for the help Jon!

For others interested, redefining barcode makes it compatible with qiime SampleIDs. 

```
        try:
            #barcode = bar_re.findall(toks[8])[0]
            barcode = toks[8].split('_')[0]
        except IndexError:
```
